shellEmulator: true

trustPolicy: no-downgrade

onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver

allowBuilds:
  esbuild: true
  sharp: true

minimumReleaseAgeExclude:
  - fumadocs-core@16.9.2
  - fumadocs-ui@16.9.2
