shellEmulator: true

trustPolicy: no-downgrade

onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver

allowBuilds:
  esbuild: true
  sharp: true

minimumReleaseAgeExclude:
  - '@fumadocs/*'
  - 'fumadocs-*'
  - '@fuma-*'
