minimumReleaseAgeExclude:
  - '@fumadocs/*'
  - 'fumadocs-*'
  - '@fuma-*'
  - '@fumari/image-size'
shellEmulator: true

trustPolicy: no-downgrade

onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver

allowBuilds:
  esbuild: true
  sharp: true
